version: '3.5'

services:
    carousel:
        image: photograhb/carousel
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        container_name: frontend