version: '3.5'

services:
    front-end:
        image: frontend
        build: 
            context: .
            dockerfile: Dockerfile_frontend
        ports:
            - 5000:5000
        container_name: frontend

    back-end:
        image: backend
        build:
            context: .
            dockerfile: Dockerfile_backend
        ports:
            - 8080:8080
        environment: 
            - REDIS_HOST=redis
            - POSTGRES_HOST=postgres
            - POSTGRES_PASSWORD=postgrespwd
            - POSTGRES_USER=haibipeng
        container_name: backend
        
    redis:
        image: redis:latest
        restart: unless-stopped
        ports:
            - 6379:6379
        container_name: redis

    postgres:
        image: postgres:latest
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=postgrespwd
            - POSTGRES_USER=haibipeng
        container_name: postgres
    
    nginx:
        image: nginx:latest
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        container_name: nginx
